JCC = javac
peerProcess: peer.class logs.class peerProcess.class process.class RemotePeerInfo.class StartRemotePeers.class
peer.class: peer.java logs.java peerProcess.java process.java RemotePeerInfo.java StartRemotePeers.java
	$(JCC) peer.java logs.java peerProcess.java process.java RemotePeerInfo.java StartRemotePeers.java
